apps/transport/urls.py
from django.urls import path
from .views.appviews import *

app_name = "transport"

urlpatterns = [
    path("routes/<int:pk>/", RouteItemView.as_view(), name="routes_item"),
    path("routes/", RouteListView.as_view(), name="routes_list"),
    path("riders/", RiderListView.as_view(), name="riders_list"),
]

project/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
]

urlpatterns += [
    path("", TemplateView.as_view(template_name="_blank.html")),
    path("transport/", include("apps.transport.urls", namespace="transport")),
]

apps/models.py
from django.core.validators import RegexValidator
from django.db import models

from qux.models import CoreModel, default_null_blank


roman2integer = {
    "I": 1,
    "II": 2,
    "III": 3,
    "IV": 4,
    "V": 5,
    "VI": 6,
    "VII": 7,
    "VIII": 8,
    "IX": 9,
    "X": 10,
    "XI": 11,
    "XII": 12,
}


PERSON_CATEGORIES = (
    ("student", "Student"),
    ("faculty", "Faculty"),
    ("staff", "Staff"),
    ("other", "Other"),
)


class Person(CoreModel):
    phone_re = RegexValidator(
        regex=r"^\+?[1-9]\d{4,14}$",
        message="Phone number must be entered in the format: '+999999999'. "
        "Up to 15 digits allowed.",
    )

    last_name = models.CharField(max_length=32)
    first_name = models.CharField(max_length=32, **default_null_blank)
    middle_name = models.CharField(max_length=64, **default_null_blank)
    category = models.CharField(
        max_length=8, choices=PERSON_CATEGORIES, default="student"
    )
    grade = models.IntegerField(**default_null_blank)
    phone = models.CharField(max_length=16, validators=[phone_re], **default_null_blank)
    email = models.EmailField(**default_null_blank)
    address = models.TextField(**default_null_blank)
    address_city = models.CharField(max_length=32, default="Pune")
    address_pincode = models.CharField(max_length=6, **default_null_blank)
    address_country = models.CharField(max_length=2, default="IN")
    is_student = models.BooleanField(default=True)
    is_teacher = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    class Meta:
        db_table = "person"
        unique_together = [
            ("first_name", "last_name"),
            ("first_name", "last_name", "phone"),
            ("first_name", "last_name", "email"),
        ]

    @classmethod
    def create_record(cls, record):
        if not hasattr(record.get("name", None), "split"):
            return None

        n = [x.strip().upper() for x in record["name"].strip().split(" ")]

        params = {
            "first_name": n[0],
            "phone": record["phone"],
            "grade": roman2integer.get(record.get("grade", None), None),
        }
        if len(n) > 1:
            params["last_name"] = n[-1]
        if len(n) > 2:
            params["middle_name"] = " ".join(n[1:-1])

        try:
            obj, created = cls.objects.get_or_create(**params)
            obj.address = record["address"]
            obj.save()
        except:
            obj = None

        return obj

    def name(self):
        result = ""
        if self.first_name:
            result = self.first_name
        if self.last_name:
            if result:
                result += " " + self.last_name
            else:
                result = self.last_name

        return result

    def catgrade(self):
        return self.grade if self.grade else self.category.upper()[0]

    def __repr__(self):
        return f"<{self.name()} :: {self.phone}>"

    def __str__(self):
        return self.name()

apps/transport/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models

from apps.models import Person
from qux.models import CoreModel, default_null_blank


class BusRoute(CoreModel):
    route = models.CharField(max_length=8, **default_null_blank)
    registration = models.CharField(max_length=10, **default_null_blank)
    name = models.CharField(max_length=128)
    teacher = models.ForeignKey(
        Person,
        on_delete=models.DO_NOTHING,
        related_name="route_bus_parent",
        **default_null_blank,
    )
    driver = models.ForeignKey(
        Person,
        on_delete=models.DO_NOTHING,
        related_name="route_driver",
        **default_null_blank,
    )
    attendant = models.ForeignKey(
        Person,
        on_delete=models.DO_NOTHING,
        related_name="route_attendant",
        **default_null_blank,
    )
    whatsapp = models.URLField(max_length=128, **default_null_blank)
    data = models.JSONField(**default_null_blank)

    class Meta:
        verbose_name = "Bus Route"
        ordering = ["route", "id"]

    def __repr__(self):
        return f"<{self.id}: [{self.route}] {self.name}>"

    def __str__(self):
        return f"{self.route}"

    @classmethod
    def create_record(cls, route):
        print(route)

        obj = cls()
        obj.name = str(route["name"])
        obj.data = route
        obj.save()

        return obj

    def as_dict(self):
        result = self.to_dict()
        result["id"] = self.id
        result.pop("data")
        print(result)
        return result


class BusRider(CoreModel):
    rider = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    route = models.ForeignKey(
        BusRoute, on_delete=models.DO_NOTHING, related_name="route_riders"
    )
    area = models.CharField(max_length=64, **default_null_blank)
    time = models.TimeField(**default_null_blank)

    class Meta:
        verbose_name = "Bus Rider"
        ordering = ["route", "rider"]
        unique_together = [("route", "rider")]

apps/transport/views/appviews.py
from django.views.generic import TemplateView, DetailView, ListView

from ..models import BusRoute, BusRider


class RouteListView(TemplateView):
    template_name = "routes/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["data"] = [x.as_dict() for x in BusRoute.objects.all()]
        return context


class RouteItemView(DetailView):
    template_name = "routes/item.html"
    queryset = BusRoute.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["riders"] = BusRider.objects.filter(
            route_id=self.kwargs.get("pk", None)
        ).order_by("route__route", "time", "rider__last_name")

        return context


class RiderListView(ListView):
    template_name = "riders/list.html"
    queryset = BusRider.objects.all()

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        if "pk" in self.kwargs:
            queryset = queryset.filter(route_id=self.kwargs["pk"])

        grade = self.request.GET.get("grade", None)
        if grade:
            if grade == "F":
                queryset = queryset.filter(rider__category="faculty")
            else:
                queryset = queryset.filter(rider__grade=grade)
        if "category" in self.request.GET:
            queryset = queryset.filter(rider__category=self.request.GET["category"])

        queryset = queryset.order_by("route__route", "time", "rider__last_name")

        return queryset

apps/transport/templates/riders/list.html
{% include "_blank.html" %}

{% block qux_content %}
{% include "riders/table.html" with route_info=True %}
{% endblock qux_content %}

apps/transport/templates/riders/table.html
<table class="table table-sm table-striped">
<thead>
  <tr>
    <th>Name</th>
    <th>Grade</th>
    <th>Phone</th>
    {% if route_info %}
    <th>Route</th>
    <th>Bus</th>
    {% endif %}
    <th>Area</th>
    <th>Time</th>
  </tr>
</thead>

<tbody>
{% for obj in object_list %}
  <tr>
    <td>{{ obj.rider.last_name }}, {{ obj.rider.first_name }}</td>
    <td><a href="{% url 'transport:riders_list' %}?grade={{ obj.rider.catgrade }}">
      {{ obj.rider.catgrade }}
    </a></td>
    <td>{{ obj.rider.phone }}</td>
    {% if route_info %}
    <td><a href="{% url 'transport:routes_item' obj.route.id %}">
      Route {{ obj.route }}
    </a></td>
    <td>{{ obj.route.registration }}</td>
    {% endif %}
    <td>{{ obj.area }}</td>
    <td>{{ obj.time }}</td>
  </tr>
{% endfor %}
</tbody>
</table>

apps/transport/templates/routes/item.html
{% extends "_blank.html" %}

{% block qux_content %}
<div class="container-fluid">
  <div class="my-3">
    <div class="row">
      <div class="col-12 col-md-4">Route</div>
      <div class="col-12 col-md-8">{{ object.route }}</div>
    </div>
    <div class="row">
      <div class="col-12 col-md-4">Bus</div>
      <div class="col-12 col-md-8">{{ object.registration }}</div>
    </div>
    <div class="row">
      <div class="col-12 col-md-4">Name</div>
      <div class="col-12 col-md-8">{{ object.name }}</div>
    </div>
    <div class="row">
      <div class="col-12 col-md-4">Teacher</div>
      <div class="col-12 col-md-8">{{ object.teacher }}</div>
    </div>
    <div class="row">
      <div class="col-12 col-md-4">Driver</div>
      <div class="col-12 col-md-8">{{ object.driver }}</div>
    </div>
    <div class="row">
      <div class="col-12 col-md-4">Attendant</div>
      <div class="col-12 col-md-8">{{ object.attendant }}</div>
    </div>
    <div class="row border-top my-4 no-gutters pt-4">
      <div class="col-12 col-md-4">WhatsApp</div>
      <div class="col-12 col-md-8">
        <a href="{{ object.whatsapp }}">{{ object.whatsapp }}</a>
      </div>
    </div>
  </div>

  <div class="my-3">
  {% include "riders/table.html" with object_list=riders route_info=False %}
  </div>
</div>
{% endblock %}

apps/transport/templates/routes/list.html
{% include "_blank.html" %}

apps/transport/templates/routes/table.html
<table class="table table-sm table-striped">
<thead>
  <tr>
    <th>Route</th>
    <th>Bus</th>
    <th>Name</th>
    <th>Teacher</th>
    <th>Attendant</th>
    <th>Driver</th>
  </tr>
</thead>

<tbody>
{% for obj in object_list %}
  <tr>
    <td>{{ obj.route }}</td>
    <td>{{ obj.registration }}</td>
    <td>{{ obj.name }}</td>
    <td>{{ obj.teacher.name }}</td>
    <td>{{ obj.attendant }}</td>
    <td>{{ obj.driver }}</td>
  </tr>
{% endfor %}
</tbody>
</table>

templates/_blank.html
{% extends '_seo.html' %}
{% load static i18n qux %}
{% lineless %}

{% block application_name %}Analog Stack{% endblock %}
{% block apple_mobile_web_app_title %}Analog Stack{% endblock %}
{% block icon %}{% static '/logo/qux.svg' %}{% endblock %}

{% block keywords %}{{ meta.keywords }}{% endblock %}

{% block title_prefix %}Analog Stack{% endblock %}

{% if meta.description %}
{% block meta_description %}{{ meta.description }}{% endblock %}
{% block og_description %}{{ meta.description }}{% endblock %}
{% block twitter_description %}{{ meta.description }}{% endblock %}
{% endif %}

{% if meta.page_title %}
{% block title %} {{ meta.page_title|default_if_none:"" }}{% endblock %}
{% block og_title %} {{ meta.page_title|default_if_none:"" }}{% endblock %}
{% endif %}

{# Facebook Open Graph #}
{% block og_url_prefix %}https://analogstack.com/{% endblock %}
{% block og_site_name %}Analog Stack{% endblock %}
{% block og_title_prefix %}Analog Stack{% endblock %}
{% block og_image %}https://analogstack.com/static/logo/logo.png{% endblock %}

{# Twitter Card #}
{% block twitter_site %}@analogstack{% endblock %}
{% block twitter_site_id %}@analogstack{% endblock %}
{% block twitter_title_prefix %}Analog Stack{% endblock %}
{% block twitter_creator %}@analogstack{% endblock %}"/>
{% block twitter_creator_id %}@analogstack{% endblock %}"/>
{% block twitter_image %}https://analogstack.com/static/logo/logo.png{% endblock %}

{% block canonical_prefix %}https://analogstack.com{% endblock %}
{% block canonical %}{{ meta.canonical }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/site.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/qux.css' %}">
<!-- FontAwesome -->
<link rel="stylesheet" href="{% static 'css/all.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}">
<!-- Overloaded bootstrap -->
<link rel="stylesheet" href="{% static 'css/qux-bootstrap.css' %}">
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/all.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
{% comment %}
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script> {% endcomment %}
<script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"
    integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{# Vue #}
<script>
  window.base_url = '{{ base_url }}';
</script>
<script type="text/javascript" src="{% static 'vue/js/chunk-vendors.js' %}"></script>
<script type="text/javascript" src="{% static 'vue/js/app.js' %}"></script>
{% endblock %}

{% block navbar %}
{% include '_navbar.html' %}
{% endblock %}

{% block qux_content %}
  {{ data|json_script:"data" }}

  {% csrf_token %}
  <div id="vueapp_container">

  </div>
{% endblock qux_content %}

{% block messages %}
<!-- flash messages -->
{% include "_messages.html" %}
{% endblock %}
{% block customjs %}
{% endblock %}
{% endlineless %}

templates/_navbar.html
{% load static %}
<nav id="nav" class="navbar navbar-expand-lg navbar-fixed-top navbar-light">
  <div class="container-fluid p-0">
    <a class="navbar-brandx" href="/">
      <span class="font-weight-bold">AnalogStack</span>
    </a>

    <button type="button"
            class="navbar-toggler"
            data-toggle="collapse"
            data-target="#navbar"
            aria-expanded="false"
            aria-controls="navbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-default navbar-nav ml-auto">
        <!-- Services -->
        <li class="nav-item dropdown">
          <a href="#" class="nav-link px-md-3" data-toggle="dropdown" role="button">
            <span class="foo">Transport</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-item">
              <a href="/transport/routes/">Routes</a>
            </div>
            <div class="dropdown-item">
              <a href="#">Riders</a>
            </div>
          </div>
        </li>

        <!-- About -->
        <li class="nav-item">
          <a href="#" class="nav-link px-md-3" data-toggle="dropdown" role="button">
            <span class="foo">About Us</span>
          </a>
        </li>

        <!-- Logout -->
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="/logout/" class="nav-link px-md-3">
              Logout
            </a>
          </li>
        {% else %}
          <li class="nav-item">
          <a href="/login/" class="nav-link px-md-3">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>